### ISSUE TITLE
Toggle 'Scans uitvoeren' is redundant

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#105]
In the settings of a list there's a toggle for 'Scans uitvoeren'.

I don't really see the purpose for it. If you don't want to perform a scan, just don't press Scan and/or change the repeat function to None.

What is the rationale of the toggle? If there is none, I would suggest to remove the toggle.

**Comment by stitch** [comment]
Well spotted. Indeed, it has no purpose. It's always on for everyone currently. The no option from the frequency dropdown was also correctly coded.

The field has been removed. Scans are always on, the button is always visible.

![image](https://user-images.githubusercontent.com/333846/69155108-6b292780-0ae1-11ea-9e85-2526d2753a35.png)
