### ISSUE TITLE
report in acc.dashboard doesn't behave in (by me) expected ways

### ISSUE THREAD

**Issue by mennononhebel** [internetstandards/Internet.nl-dashboard#111]
When deselecting all the "visible metrics" i would expect to see no graphics. 
The report part (last part of the report)(when printed)  doesn't show any icons for the tests of the sites
The report part (when printed) doesn't show all the tested sites (but a slidebar)  
![image](https://user-images.githubusercontent.com/52524333/71084793-54d0c300-2196-11ea-8c7d-f689773d8712.png)

**Comment by stitch** [comment]
Todo: also add CSS print instructions. And change the table on media print.

**Comment by stitch** [comment]
Print instructions added

**Comment by mennononhebel** [comment]
Still not completely as hoped or expected: see for instance the overview of all scanned sites:

1) attachment is how adobe makes a pdf of the report
2) attachment is an example of how only 13 of the 18 sites are shown when actually printed (ctrl P) directly from the report on screen  

Best
menno

-----Original Message-----

**Comment by stitch** [comment]
There are two graphs of the right category per page:
![image](https://user-images.githubusercontent.com/333846/72879997-4aa66500-3cfe-11ea-976e-2e9f61dcbaac.png)

Table now spans multiple pages, as long as need be:
![image](https://user-images.githubusercontent.com/333846/72879883-18950300-3cfe-11ea-898f-6f2c9fc6ebeb.png)

Logo is printed correctly:
![image](https://user-images.githubusercontent.com/333846/72880027-5b56db00-3cfe-11ea-87b2-ce645aaed420.png)

Only the legend is printed, not the export or the configuration:
![image](https://user-images.githubusercontent.com/333846/72880045-6c075100-3cfe-11ea-88db-4affca1be8ef.png)

The timeline print includes the table below it:
![image](https://user-images.githubusercontent.com/333846/72880068-7c1f3080-3cfe-11ea-82ad-6838f27d7f4b.png)

The report section, as well as the graph section start on a new page:
![image](https://user-images.githubusercontent.com/333846/72880145-978a3b80-3cfe-11ea-9ec2-6634e2051e47.png)
