### ISSUE TITLE
Add username to feedback

### ISSUE THREAD

**Issue by dennisbaaten** [internetstandards/Internet.nl-dashboard#151]
When adding a user via the "Instant User Creation Form" the feedback is "Account created!". Please add the username of the user that was just created to this message, since this makes it easier to validate when adding multiple users sequentially.

**Comment by stitch** [comment]
![image](https://user-images.githubusercontent.com/333846/76961818-5b4e1280-691e-11ea-9b7b-8ee4f9f2b556.png)
