### ISSUE TITLE
No visible difference between DNSSEC e-mailaddress domain and MX in details

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#165]
![afbeelding](https://user-images.githubusercontent.com/28256969/81850373-2e059580-9558-11ea-962e-d1cc5373a2c5.png)

**Comment by stitch** [comment]
Fixed in API 2.0 version:

![image](https://user-images.githubusercontent.com/333846/81918315-9a26de80-95d6-11ea-86c0-d5da0d63fd80.png)
