### ISSUE TITLE
Trailing space prevents adding to list

### ISSUE THREAD

**Issue by dennisbaaten** [internetstandards/Internet.nl-dashboard#178]
When adding domains using the "Add domains" button, a domain name with a trailing space is not accepted. Domains on the list are separated with new line. Examples of domain names where this happened: eskillsplatform.nl, stichtingmediawijzer.nl.

**Comment by stitch** [comment]
I think something else is going on. 

The following testcase retrieves those domains without any problem. This contains random spaces, tabs and comma's before and after the domain. Perhaps it's a different invisible character, for that i've added removal of any other invisible characters.

```
    unsanitized_input = """
    ,
     stichtingmediawijzer.nl	  
            , , ,
     	 
    eskillsplatform.nl  ,        
    """
    output = retrieve_urls_from_unfiltered_input(unsanitized_input)
    assert output == ['eskillsplatform.nl', 'stichtingmediawijzer.nl']
```

What is the account affected? I can take a look.

**Comment by dennisbaaten** [comment]
I ran some tests and it appears to be the character "\xa0" which is a non-breaking space in Latin1.

**Comment by stitch** [comment]
Added even more possible whitespace characters to the test. See https://qwerty.dev/whitespace/.
