### ISSUE TITLE
Report mail scan not loading

### ISSUE THREAD

**Issue by dennisbaaten** [internetstandards/Internet.nl-dashboard#179]
Mail test with 182 domains. Scan is done, but report is not loading. #222

**Comment by stitch** [comment]
Correct, the account was missing a number of fields in its configuration. I've improved the sitation: in case no field information is available, default values are used. A user can then configure their own fields. The data that is saved then will overrule the defaults.

Code pushed, but not deployed to server yet:
https://github.com/internetstandards/Internet.nl-dashboard/tree/development
