### ISSUE TITLE
Graph colors, graphs levels and comparisons color scheme

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#18]
Currently the Forum Standaardisatie Magazine colors are used. The primary color is orange, the secondary blue. Then a random extrapolation is done (yellow, cyan, etc).

What colors could better represent "correct"?

Most color blind users would need blue and red instead of green and red.

**Comment by stitch** [comment]
We could/should also improve the graphs with "info", "warning" and "good" values. Everything that is not "error" is now 100%, which is of course susceptible to misinterpretation. It's not yet clear if we can have stacking bar charts in comparisons and how to make sure the colors stay consistent.

**Comment by stitch** [comment]
For your evaluation:

![image](https://user-images.githubusercontent.com/333846/62131650-db663000-b2db-11e9-8f6b-67c2d3256d4b.png)

**Comment by stitch** [comment]
All colors are possible. The border color is always darker for accessibility reasons.

Shapes in comparison reports can be seen here:
https://github.com/ashiguruma/patternomaly

**Comment by robinbzk** [comment]
![afbeelding](https://user-images.githubusercontent.com/28256969/65325283-b0e37580-dbae-11e9-9dff-7705c19041b2.png)
these three primary colors, please choose two colors that match. :-)

**Comment by stitch** [comment]
Looks decent!

![image](https://user-images.githubusercontent.com/333846/68384866-d295bd80-0158-11ea-9db4-29b5f5d277c2.png)

**Comment by stitch** [comment]
This is an example with 8 reports:

![image](https://user-images.githubusercontent.com/333846/68389404-23121880-0163-11ea-9a23-6970b60286b9.png)

**Comment by stitch** [comment]
The numbers are not readable anymore at a certain point, which can take a while before its reached. There is no alternative yet for these numbers, aside from leaving them out when they start to overlap. Would we do that, there should be a table below the graph with the actual data.:

![image](https://user-images.githubusercontent.com/333846/68392476-28269600-016a-11ea-9317-4af645254377.png)
