### ISSUE TITLE
DKIM 'pass' should override DKIM 'not applicable'

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#183]
If a domain does not send email, but has DKIM implemented, the 'pass' for DKIM should override the 'not applicable'

Example domain:
https://dev.batch.internet.nl/mail/rijksvastgoedbedrijf.nl/292868/#control-panel-13

![image](https://user-images.githubusercontent.com/28256969/85702506-c60da780-b6de-11ea-95c1-78a5bd0540f9.png)

![image](https://user-images.githubusercontent.com/28256969/85702573-d6be1d80-b6de-11ea-9f71-e615c4375629.png)

**Comment by stitch** [comment]
Logica omkeren:

mail_auth_dkim_exist == passed:
- dan die waarde pakken.
als die failed:
  dan checken of: mail_non_sending_domain, als mail_non_sending_domain dan not_applicable
  anders failed.

**Comment by stitch** [comment]
Implemented
