### ISSUE TITLE
TLS in extra field pass, while in regular fields not tested

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#185]
![image](https://user-images.githubusercontent.com/28256969/85730237-c8c9c600-b6f9-11ea-8a5e-faf92be09f3a.png)
![image](https://user-images.githubusercontent.com/28256969/85730327-dc752c80-b6f9-11ea-8c89-ccd7fbb45af2.png)
![image](https://user-images.githubusercontent.com/28256969/85730414-ebf47580-b6f9-11ea-93eb-b50cecf94879.png)

https://dev.batch.internet.nl/site/www.zundert.nl/671859/

**Comment by stitch** [comment]
add_calculation(scan_data=scan_data, new_key='web_legacy_tls_available',
                    required_values=['web_https_http_available'])

**Comment by stitch** [comment]
lowest_test_status = "passed" -> dat gaat fout daarom. Er zit een mismatch in.

**Comment by stitch** [comment]
Missed 'error' in lowest_value_in_results

**Comment by stitch** [comment]
Fixed.
