### ISSUE TITLE
Improvements to Extra Fields and Excel output

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#205]
We want to apply some additional logic for the Extra Fields to remove ambiguity from the results, and make some UI improvements to the Excel output and specifically to the visualization of the Extra Fields results.

### Adjustments to Extra Fields
- [x] When "Mail server has MX record" is false, then IPv6 nameserver becomes "no_mx". This shouldn't happen, as even without an MX, the nameserver should still be reachable over IPv6.
- [x] In the category _IPv6_ field (only in Extra fields) values should become _no_mx_ if the _IPv6 mailserver_ is also _no_mx_.
- [x] Values are missing for IPv6 (web test, Extra Fields) in the Excel output, add values.
- [x] Rename category _IPv6_ (only in Extra fields) to _IPv6 web_ in the webtest, and to _IPv6 mail_ in the mailtest
- [x] Rename field _HTTPS_ to _HTTPS redirect_ (UI and export)
- [x] Translate not_tested into a value interpretation: infer the result from the primary/superior/parent test; overwrite the API result with the primary/superior/parent test result. (UI and export)
_
 _Web:_
_TLS NCSC web, HTTPS enforced, HSTS, DANE_ are dependant on _TLS available_
_
 _Mail:_
_DMARC policy_ is dependant on _DMARC_
_SPF policy_ is dependant on _SPF_
_DANE_ is dependant on _STARTTLS_
_
(I believe these are all the fields that may contain the _not_tested_ value in the Extra Fields)
_
- [x] Rename value _not_testable_ to _untestable_ (as per API field _mail_servers_testable_status_) (UI and export)
- [x] In the bar charts, group _unreachable_ and _untestable_ (and regular _error_) into a category _test error_ (UI and totals row Excel)
- [x] In the bar charts, group _not_tested_ results in a separate category _not_tested_ (UI and totals row Excel)

> _not_tested_ resultaten moeten in de categorie _not tested_ terugkomen
> _not_testable_ (of _untestable_) resultaten moet in de categorie _test error_ terugkomen

- [x] In the bar charts, group _no_mx_ and _not_applicable_ into a category _not applicable_ (UI and totals row Excel)
- [x] In the dashboard UI, for _no_mx_ and _not_applicable_ detailed results, use the _Not tested icon_.
- [x] In the dashboard UI, for _unreachable_ and _untestable_ detailed results, use the _Error icon_.
- [x] Inverse "non sending domain" to sending domain, use only pass and fail
- _Non email sending domain_' becomes '_Email sending domain_'
- We want _passed_ when the domain _does_ send email
- We want _failed_ when the domain _does not send_ email
- This might affect the logic that is used to indicate _no_mx_
![image](https://user-images.githubusercontent.com/28256969/87521202-57d85700-c684-11ea-9a93-f28735de0d07.png)

### Improve Excel output in general
- [x] 1. Percentage passed (ignoring not_tested): it is probably misleading to ignore not_tested, because not_tested can either be because it would fail automatically because the parent test failed, or it didn't run because of a test error. I think it shouldn't ignore not_tested.
- [x] 2. For both web and mail output, please add a new totals row called _Contains test errors_ which is the sum of all values _error_, _unreachable_ and _untestable_
- [x]  3. _For the mail test_ please add a new totals row called _Test not applicable_ which is the sum all values _no_mx_ and _not_applicable_
- [x] 4. For both web and mail output, freeze panes (titelblokkering) 1 row lower (so column titles (subtest field names) are 'sticky')
- [x] give column G (with the batch.internet.nl links) a title (for example _Test report_)
- [x] If columns C, D and E have no purpose, see if they could be removed from the Excel output (they seem always the same, no real values?)

**Comment by stitch** [comment]
Screenshot excel output improvements:
![image](https://user-images.githubusercontent.com/333846/94909817-092ca300-04a4-11eb-9953-c2d8e9c601f2.png)

**Comment by stitch** [comment]
More excel upgrades:

![Uploading image.png…]()

**Comment by robinbzk** [comment]
> When "Mail server has MX record" is false, then IPv6 nameserver becomes "no_mx". This shouldn't happen, as even without an MX, the nameserver should still be reachable over IPv6.

In addition to this, in the category _IPv6_ field (only in Extra fields) the value should become _no_mx_ if the IPv6 mailserver is also _no_mx_.

Also, could you rename category _IPv6_ (only in Extra fields) to _IPv6 web_ in the webtest, and to _IPv6 mail_ in the mailtest?

**Comment by stitch** [comment]
> > When "Mail server has MX record" is false, then IPv6 nameserver becomes "no_mx". This shouldn't happen, as even without an MX, the nameserver should still be reachable over IPv6.
> 
> In addition to this, in the category _IPv6_ field (only in Extra fields) the value should become _no_mx_ if the IPv6 mailserver is also _no_mx_.
> 
> Also, could you rename category _IPv6_ (only in Extra fields) to _IPv6 web_ in the webtest, and to _IPv6 mail_ in the mailtest?

Can you add this to the original post in the checklist? That prevents fragmentation of these fixes.

**Comment by robinbzk** [comment]
Perhaps you could give column G (with the batch.internet.nl links) a title (for example _Test report_)

Perhaps columns C, D and E could be removed from the Excel output (they are always the same, no real values)?

**Comment by robinbzk** [comment]
> 
> 
> > > When "Mail server has MX record" is false, then IPv6 nameserver becomes "no_mx". This shouldn't happen, as even without an MX, the nameserver should still be reachable over IPv6.
> > 
> > 
> > In addition to this, in the category _IPv6_ field (only in Extra fields) the value should become _no_mx_ if the IPv6 mailserver is also _no_mx_.
> > Also, could you rename category _IPv6_ (only in Extra fields) to _IPv6 web_ in the webtest, and to _IPv6 mail_ in the mailtest?
> 
> Can you add this to the original post in the checklist? That prevents fragmentation of these fixes.

Done

**Comment by stitch** [comment]
The other excel upgrades:

![image](https://user-images.githubusercontent.com/333846/94930975-7867be80-04c7-11eb-9a9e-239d71432beb.png)

**Comment by stitch** [comment]
For: "Rename value not_testable to untestable (as per API field mail_servers_testable_status) (UI and export)"

The following fields can have not_testable:
- web_legacy_tls_1_3
- mail_legacy_start_tls
- mail_legacy_start_tls_ncsc
- mail_legacy_dane
- mail_legacy_tls_1_3

Should all of these be renamed to "untestable"?

**Comment by robinbzk** [comment]
> For: "Rename value not_testable to untestable (as per API field mail_servers_testable_status) (UI and export)"
> 
> The following fields can have not_testable:
> 
> * web_legacy_tls_1_3
> * mail_legacy_start_tls
> * mail_legacy_start_tls_ncsc
> * mail_legacy_dane
> * mail_legacy_tls_1_3
> 
> Should all of these be renamed to "untestable"?

Yes, best to keep terminology used in API and dashboard as close to each other as possible.

**Comment by stitch** [comment]
For this issue: "In the category IPv6 field (only in Extra fields) values should become no_mx if the IPv6 mailserver is also no_mx."

mail_servers_testable_status no_mx depends on "mail_servers_testable_status", there is no distinction in ipv4 or ipv6...

**Comment by stitch** [comment]
Some notes because some checks impact both websecmap and the dashboard, and websecmap is edited first:

Todo on dashboard: 
- [ ] Replace mail_legacy_mail_non_sending_domain with mail_legacy_mail_sending_domain
- [ ] Rename not_testable to untestable

**Comment by stitch** [comment]
> > For: "Rename value not_testable to untestable (as per API field mail_servers_testable_status) (UI and export)"
> > The following fields can have not_testable:
> > 
> > * web_legacy_tls_1_3
> > * mail_legacy_start_tls
> > * mail_legacy_start_tls_ncsc
> > * mail_legacy_dane
> > * mail_legacy_tls_1_3
> > 
> > Should all of these be renamed to "untestable"?
> 
> Yes, best to keep terminology used in API and dashboard as close to each other as possible.

I've made this into a cosmetic change on the dashboard, given that 'not_testable' is used in many places in the software (statistics calculation and other places). I think this is enough as it's just a label. It will do this in the ui and spreadsheet:

Is that enough?

![image](https://user-images.githubusercontent.com/333846/94943105-8291b900-04d7-11eb-9b2c-98d3e8b654c7.png)

![image](https://user-images.githubusercontent.com/333846/94943209-9ccb9700-04d7-11eb-98a2-48964ad714e7.png)

**Comment by stitch** [comment]
> > > For: "Rename value not_testable to untestable (as per API field mail_servers_testable_status) (UI and export)"
> > > The following fields can have not_testable:
> > > 
> > > * web_legacy_tls_1_3
> > > * mail_legacy_start_tls
> > > * mail_legacy_start_tls_ncsc
> > > * mail_legacy_dane
> > > * mail_legacy_tls_1_3
> > > 
> > > Should all of these be renamed to "untestable"?
> > 
> > 
> > Yes, best to keep terminology used in API and dashboard as close to each other as possible.
> 
> I've made this into a cosmetic change on the dashboard, given that 'not_testable' is used in many places in the software (statistics calculation and other places). I think this is enough as it's just a label. It will do this in the ui and spreadsheet:
> 
> Is that enough?
> 
> ![image](https://user-images.githubusercontent.com/333846/94943105-8291b900-04d7-11eb-9b2c-98d3e8b654c7.png)
> 
> ![image](https://user-images.githubusercontent.com/333846/94943209-9ccb9700-04d7-11eb-98a2-48964ad714e7.png)

I see that there is a mismatch between untestable and not_tested. But not_tested should be overwritten anyway with a 'parent' value, so we can ignore this i guess...
