### ISSUE TITLE
Use EU resolvers for prechecks

### ISSUE THREAD

**Issue by baknu** [internetstandards/Internet.nl-dashboard#250]
Randomly use the following European DNS resolvers that do DNSSEC validation for domain name prechecks:

- https://www.nic.cz/odvr/
- https://www.switch.ch/security/info/public-dns/ 

Other alternative: 
- https://blog.uncensoreddns.org/dns-servers/

Regarding https://dns.watch: it is not clear who is behind this service. So let's not use this one.

**Comment by baknu** [comment]
We could probably also use TransIP's resolvers for this: https://www.transip.nl/knowledgebase/artikel/3574-de-dns-resolvers-van-vps-aanpassen/

**Comment by stitch** [comment]
Let's try transip first, let's see if SIDN has one. Then use the other european ones.

**Comment by stitch** [comment]
switch.ch doesn't work. transip doesn't work (probably a config thing)

Currently testing with: 
CZ.NIC:
["193.17.47.1", "185.43.135.1",

UncencoredDNS:
 "130.225.244.166"]
