### ISSUE TITLE
Send compliance/conformity results to specific contacts per domain

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#252]
- As a dashboard user I want to send compliance/conformity information to specific contacts (e.g. administrator, security officer) for the specific domains, so the responsible person can use that information to improve the domain compliance.

By automating this step, I don't have to manually send every person a personalized e-mail to improve compliance.

This would imply that a contact e-mail address is known for a specific domain that is in your dashboard.

I can imagine that instead of linking an e-mail address to a domain, it could be more user friendly to link an e-mail address to an organization, and that a domain is linked to an organization.
Example: `<domain>www.internet.nl</domain>` is part of `<organization>Platform Internetstandaarden</organization>` and I will send conformity information to `<contact>vraag@internet.nl</contact>`

**Comment by stitch** [comment]
Duplicate of #459
