### ISSUE TITLE
More flexibility in creating dashboard reports through metadata for domains

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#253]
As a dashboard user I want more flexibility in creating dashboard reports, so that I can serve the needs of people that are interested in seeing different cross-sections of scan results dynamically.

- A solution could be to have domains as the central assets in the dashboard instead of lists.
- A domain could then have metadata (organizational labels (team, unit, department, company, association), functional labels (parking page, email domain), technical labels (windows server, apache)), that can be used to sort or select domains for use in reports.

Background:
- Currently the dashboard is organized in lists. Lists represent a collective set of domains that I scan for a specific purpose. These purposes are flexible and change over time. Now I am forced to create a new list for every scan purpose. The number of lists in my dashboard is exploding. The same domain name can be in many lists.
- When I present a report, I am often asked for more detailed representations. For example: I scan a list of all central government domains, I am later asked to sort the domains per ministry. As I didn't have a list per ministry, it is either a lot of manual labour to edit the Excel output, or I have to make new lists and create new scans.

**Comment by stitch** [comment]
Based on feedback on key users.

Scans based on tags. Or scan all domains and then create reports per tag.

Reports and scans will not change that much. The "list management" will change, as the scanning method as we'll scan everything the user has.

Find software that manages tags well, and makes it easy to reuse.
Rework the list management interface.

**Comment by stitch** [comment]
Tags can be added in the domain list:
![image](https://user-images.githubusercontent.com/333846/134920286-851537b6-b9d5-47c6-96d6-941a1bd9df4e.png)


Tags can be used as a filter to create an ad-hoc report.
![image](https://user-images.githubusercontent.com/333846/134920188-e1a03c66-f782-4ab2-bfee-bfbd1694127f.png)



The ad-hoc report can be saved as a separate report (but does not create a separate list(!)):
![image](https://user-images.githubusercontent.com/333846/134920377-ae0647e1-729b-4ad5-b0ff-65683e9a71f2.png)


The expert options are only available for superusers, this is handled in another issue.

This feature is now in beta and feedback will be handled in separate issues.
