### ISSUE TITLE
Also scan the www. subdomain (if it exists) for bare domains

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#255]
As the use of www. subdomains is quite ubiquitous, it would probably be good to automatically also scan the www. domain (if it exists) when scanning bare domains.

This is probably applicable for both web and e-mail scans. The www. subdomains could probably be abused for e-mailspoofing purposes.

**Comment by stitch** [comment]
Redirects and HSTS issues can be easier identified this way.

First iteration:
Make sure the list stays the same. So when the scan the www. subdomain is tried and if it resolves it will be added to the scan. (don't use www.www).

Other way around: 
test 2nd level domain when it's missing but www is there.

Second step:
How to visualize this in the UI? Probably nothing has to change.

**Comment by baknu** [comment]
When implementing, take Public Suffix list into account: https://wiki.mozilla.org/Public_Suffix_List
