### ISSUE TITLE
Geen mailresultaten coa.nl en rekenkamer.nl 

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#260]
![image](https://user-images.githubusercontent.com/28256969/107640984-4fc0b400-6c73-11eb-99c4-160af62b94cd.png)

Zie rapporten 1752 en 1763 waar dit voorkomt.

Op internet.nl zijn deze domeinen wel te testen: https://internet.nl/mail/coa.nl/481001/ https://internet.nl/mail/rekenkamer.nl/481002/

**Comment by stitch** [comment]
Opgelost:

![image](https://user-images.githubusercontent.com/333846/107671976-af7b8700-6c94-11eb-8512-5254f533f08d.png)
