### ISSUE TITLE
Scans performed as impersonated user get notifications on the impersonating user's email address.

### ISSUE THREAD

**Issue by aequitas** [internetstandards/Internet.nl-dashboard#264]
Als administrator gebruik ik wel eens de "impersonate" functie van het
dashboard middels de button "switch user". Wanneer ik daarna niet terug
switch naar mijn eigen account en de browser sluit (c.q. uitlog) dan
ontvang ik mail notificaties van uitgevoerde scans van het andere
account op mijn eigen e-mailadres.

**Comment by aequitas** [comment]
@stitch is dit verwacht gedrag of een bug?

**Comment by robinbzk** [comment]
Mij is hetzelfde opgevallen. En gaan er dan géén notificaties meer naar de originele gebruiker?

**Comment by stitch** [comment]
@aequitas 
Dit is zo bedoeld: als je onderdeel wordt van een andere organisatie dan worden je mail instellingen behouden. Je krijgt dus ook de mails van die organisatie. Wat gebeurd is dat het gebruikersaccount aan een andere organisatie wordt gekoppeld. Beheerders kunnen vrij van accounts wisselen: het is denk ik naamsverwarring over wat 'account' betekent. In het geval van het dashboard is een account iets waar meerdere gebruikers onder zitten.

@robinbzk 
Mail wordt ingesteld per persoon. Dus de andere personen in die organisatie krijgen ook gewoon mail als dat is ingesteld.
