### ISSUE TITLE
Report domeinlijst score in aparte kolom

### ISSUE THREAD

**Issue by MartinMulder** [internetstandards/Internet.nl-dashboard#28]
Op een report pagina staat de lijst met domeinen.
Achter de domeinnaam staat het percentage dat dit domein voldoen (link).
Deze graag in een aparte kolom plaatsten

**Comment by stitch** [comment]
Done:

![image](https://user-images.githubusercontent.com/333846/62132485-73184e00-b2dd-11e9-8ecd-e9a96d5c78ab.png)
