### ISSUE TITLE
report domeinlijst kolommen sorteerbaar maken

### ISSUE THREAD

**Issue by MartinMulder** [internetstandards/Internet.nl-dashboard#29]
Op de rapporten pagina staat een tabel met domeinen.
De kolommen in deze tabel zou ik graag sorteerbaar zien.
Hierdoor wordt het mogelijk om alle kruisjes/vinkjes van een bepaalde kolom bij elkaar te zien (bijvoorbeeld: welke domeinen hebben IPv6)

Hierdoor wordt het ook mogelijk om na implementatie van #28 te sorteren op hoe goed een domein voldoet.

**Comment by stitch** [comment]
Make sure all columns are sortable, including score. Check if Vue-Bootstrap uses A11Y that is needed for this. Otherwise implement buttons to sort.

**Comment by stitch** [comment]
![image](https://user-images.githubusercontent.com/333846/69151511-0c60af80-0adb-11ea-85d0-8371b8d41b1e.png)
