### ISSUE TITLE
Indicatie van gewijzige domeinlijst

### ISSUE THREAD

**Issue by MartinMulder** [internetstandards/Internet.nl-dashboard#30]
Ik kan een scan uitvoeren op basis van een domeinlijst en daarna de lijst aanpassen.
Als er vervolgens een 2e scan gedaan wordt en deze 2 in een rapport vergeleken worden dan zijn de percentages verschillend. Op zich is dit natuurlijk terecht, maar dit kan verwarrend overkomen.
Het is niet mogelijk om te zien of er domeinen beter/minder presteren, of dat de lijst met domeinen is aangepast.

Het zou handig kunnen zijn om een info message te plaatsen dat de domeinen lijst is aangepast tussen de 2 scans

**Comment by stitch** [comment]
When there are differences, a warning is issued mentioning the differences.
![image](https://user-images.githubusercontent.com/333846/72890304-e7263280-3d11-11ea-89bc-d7d7b434ecf7.png)

When the lists are equal:
![image](https://user-images.githubusercontent.com/333846/72890367-ff964d00-3d11-11ea-8944-b22b616dd322.png)

Json call: data/report/differences_compared_to_current_list/23/
