### ISSUE TITLE
API voor dashboard

### ISSUE THREAD

**Issue by MartinMulder** [internetstandards/Internet.nl-dashboard#31]
Ik zou graag een API zien voor bepaalde functionaliteit van het dashboard.
Op dit moment vooral voor het aanpassen van de domeinlijsten, zodat het mogelijk wordt om deze lijsten automatisch te updaten als er domeinen bij komen / weg gaan

**Comment by stitch** [comment]
De API is er in principe al. Het enige wat nog wat ouderwetsch is, is dat je met HTTP requests moet inloggen. Voor de rest kan je JSON calls gebruiken over HTTP zolang je je cookie meestuurt. Met python requests zou je daar uit moeten komen bijvoorbeeld.

**Comment by MartinMulder** [comment]
welke endpoints moet ik hiervoor gebruiken, en is er enige vorm van documentatie betreft bericht specificatie en beschikbare endpoints?

**Comment by stitch** [comment]
Het wordt niet officeel gesupport, dus de volgende instructies kunnen spontaan wijzigen. Grofweg zal de aanpak wel hetzelfde blijven.

De API gaat over HTTP, dus je moet doen wat een browser doet. Je kan dat bijvoorbeeld met de python request library voor elkaar krijgen. Bijna alles in het dashboard gaat met JSON api's, waarvan ik diegeen die je aangaf kort heb gedocumenteerd. 

Als je een proxy zoals burp suite (of zelfs de web inspector in je browser) gebruikt, kan je ook heel makkelijk de API details voor niet genoemde pagina's vinden. Alle functionaliteit van het dashboard staat hier: https://github.com/internetstandards/Internet.nl-dashboard/blob/master/dashboard/internet_nl_dashboard/urls.py

De ID's zijn context afhankelijk en meestal straightforward. Die zijn er voor lijsten, domeinen, scans, rapporten e.d.

Voordat je de API kan gebruiken moet je ingelogd zijn. Je moet dus ook altijd je session_id meesturen in de juiste headers. Met de python request library (en dergelijke) is dat kinderspel omdat die dit al voor je automatiseert en je alleen met de applicatie zelf bezig hoeft te zijn. Je zult ook het CSRF token moeten ophalen, die moet je meesturen als je iets wil opsturen (POST). De CSRF staat bij de inlogpagina op de pagina, bij de JSON functionaliteit kan je em uit de cookies halen na inloggen.

Inloggen:
Voor inloggen moet je eerst de loginpagina ophalen, hieruit krijg je een csrfmiddlewaretoken, die moet je meeposten, deze veranderd iedere poging. Na inloggen krijg je een sessiecookie en een ander csrf token in een cookie. Deze moet je meesturen bij aanvragen.
```
POST /account/login/
csrfmiddlewaretoken=TOKEN&login_view-current_step=auth&auth-username=USERNAME&auth-password=PASSWORD
```

Lijsten ophalen:
```
GET /data/urllists/get/
```

Lijst inhoud ophalen:
```
GET /data/urllist_content/get/4/
```

Domeinen toevoegen aan lijst:
Let op, bij POST altijd het X-CSRFToken meesturen. Deze vind je in je cookies.
```
POST /data/urllist/url/add/
{"urls":"www.tweakers.net www.nu.nl","list_id":1}
```

URL aanpassen in lijst:
```
POST /data/urllist/url/save/
{"list_id":1,"url_id":1,"new_url_string":"internet2.nl"}
```

Scan aanvragen:
```
POST /data/urllist/scan_now/
{"id":1}
```

Rapport ophalen:
```
GET /data/report/get/14/
```

Hopelijk kan je hier een tijdje meer vooruit!

**Comment by stitch** [comment]
Mocht je een scriptje maken o.i.d. dan is een github linkje handig: misschien dat anderen er ook wat aan hebben :)
