### ISSUE TITLE
Missende vertaling bij het toevoegen van een scan aan een rapport

### ISSUE THREAD

**Issue by MartinMulder** [internetstandards/Internet.nl-dashboard#32]
Als ik een scan toevoeg aan een rapport krijg ik een loader met daar achter de tekst "loading.loading".
Dit lijkt een missende vertaling.
Dit komt alleen voor bij de taal instelling nederlands

**Comment by stitch** [comment]
Niet reproduceerbaar in NL en EN. Mogelijk was toen de vertaling nog niet bijgewerkt. Als je het weer tegenkomt graag dit issue weer openen :)

![image](https://user-images.githubusercontent.com/333846/62042212-db8ffe00-b1fd-11e9-9a83-d55f108fe3de.png)
