### ISSUE TITLE
Add tag support to spreadsheets (uploads)

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#326]
Voeg tagging support toe aan spreadsheets, zodat het bewerken makkelijker gaat.

Zoals: als het domein al in de lijst zit, werk dan de tags bij naar de waarde uit de spreadsheet.

nav feedback key users

**Comment by robinbzk** [comment]
As a dashboard user I would also like to export a list with domains including its tags (so I can manage/modify a list of domains and its related tags easier outside the dasboard)

**Comment by robinbzk** [comment]
- Perhaps the 'import domains from spreadsheet (including tags)'-feature could be added to the 'Add domains' functionality.
- It would be nice if there was an option (checkbox) to _overwrite_ the whole list with the spreadsheet upload. That would make it easier to delete redundant domains in bulk (currently one would have to delete domains one by one, this is tedious in lists with hundreds or thousands of domains).

![image](https://user-images.githubusercontent.com/28256969/144413740-9844f448-e94a-412f-a1d7-d9cdcb9e0e9c.png)

**Comment by bwbroersma** [comment]
Demo issue: sort download (like in dashboard view).

**Comment by stitch** [comment]
![image](https://user-images.githubusercontent.com/333846/233104557-57ff8154-8c7a-4525-a6a6-f520dbb6d19e.png)

**Comment by robinbzk** [comment]
Is https://github.com/internetstandards/Internet.nl-dashboard/issues/326#issuecomment-984545388 also part of this enhancement?

**Comment by robinbzk** [comment]
> Is [#326 (comment)](https://github.com/internetstandards/Internet.nl-dashboard/issues/326#issuecomment-984545388) also part of this enhancement?

@stitch
