### ISSUE TITLE
Dashboard report doesn't show directly from Chromium browser

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#337]
When I use a direct link to a report (either from the scans page or by typing it directly in the browser), the report doesn't show directly.
I need to manually 'Select report' for it to show.
Tried on Edge (office desktop) and Chrome (home desktop), same result.

This happens with all reports. Example:

![image](https://user-images.githubusercontent.com/28256969/142661652-8d6f9e46-02ad-4cfd-b0a3-a9cac60a60ac.png)

**Comment by stitch** [comment]
Solved in 4.2.

https://acc.dashboard.internet.nl/#/report/1117

![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/b4bea891-b244-4f20-b474-15e68536285e)
