### ISSUE TITLE
When initially sharing a report with a password, a password isn't actually set

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#339]
When sharing a report for the first time, and setting a password with it, the password isn't actually set.
You need to set the password again for it to actually ask for it when opening the shared page.

![image](https://user-images.githubusercontent.com/28256969/142668515-978989d1-e1e7-4029-93a7-a49c5eb142f7.png)

**Comment by stitch** [comment]
Dit lijkt een UI issue. Het is niet duidelijk dat een wachtwoord ook "ingesteld" moet worden met een knop. Dit moet worden versimpeld.

**Comment by stitch** [comment]
Also see #463

**Comment by stitch** [comment]
Fixed. Wrong property was checked for the current password.
