### ISSUE TITLE
Public reports: show latest report of a specific list

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#340]
- Currently it is only possible to publish individual reports made at a certain point in time. Each report gets an individual permalink.
- It would be convenient to be able to have a permanent link to the latest public report of a specific list, this reduces administrative burden to update and spread the link to a new measurement.
- It would be nice if this 'latest report of a list' also shows improvements and regressions compared to the previous measurement for individual results (existing feature when comparing reports).

**Comment by stitch** [comment]
Het laatste rapport van een lijst is altijd in te zien op de volgende url, mits gedeeld natuurijk:
https://acc.dashboard.internet.nl/#/latest/183/mail/
https://acc.dashboard.internet.nl/#/latest/183/web/
of 
https://acc.dashboard.internet.nl/#/latest/183/


Nieuwe rapporten kunnen nu automatisch worden gedeeld op een publieke pagina:
![image](https://user-images.githubusercontent.com/333846/233098159-383f8dac-a5fa-4183-8ebe-9cee9488703f.png)

De instellingen hiervan:
![image](https://user-images.githubusercontent.com/333846/233098548-0d71fb76-c88e-4a3c-8109-dcd96f895254.png)
