### ISSUE TITLE
Label function not working

### ISSUE THREAD

**Issue by dennisbaaten** [internetstandards/Internet.nl-dashboard#344]
1. I click on a list under 'Domains'
2. I select a random domain in that list
3. I type the name of a new label in the 'select label' field
4. I click the '+' button next to the 'select label' field

Result: nothing happens, no label created.
Tested in Firefox and Chrome

**Comment by stitch** [comment]
Due to this being a selectbox some other trickery needed to be performed to add the value while searching the selectbox. It seems to work pretty nicely in the 4.3 version. Also the tags have been made clickable, which was also an oversight.
