### ISSUE TITLE
Dashboard report data loading slowly or not at all

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#356]
The data of reports in the dashboard is currently loading very slowly, or sometimes not at all.

**Comment by robinbzk** [comment]
Apparantly my internet is simply not fast enough, and I guess it times out.
Is it possible to increase the timeout period?

**Comment by stitch** [comment]
Solved in 4.2 by adding compression, removing data and changing how the view works. See other issues regarding slow report performance.
