### ISSUE TITLE
Inloggen werkt niet, alleen via de alternatieve inlogpagina

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#357]
Via https://dashboard.internet.nl/#/login kom ik niet meer ingelogd vanuit Edge (chromium) en Firefox. Als ik na het invullen van mijn credentials klik op 'inloggen' gebeurt er niks. 

Via https://dashboard.internet.nl/account/login/ kom ik wel ingelogd.

**Comment by dennisbaaten** [comment]
Door een bug worden cookies niet goed gezet, en daardoor lukt het inloggen op de eerste URL niet. Verder hangt dit samen met https://github.com/internetstandards/Internet.nl-dashboard/issues/352 waarin we het inlogproces willen vereenvoudigen.

**Comment by stitch** [comment]
Duplicate of #352
