### ISSUE TITLE
Excel output mail columns 'internet_nl_mail_legacy_category' and 'E-mail sending domain' give question mark results

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#358]
![image](https://user-images.githubusercontent.com/28256969/149321519-017dd182-bad7-49a4-90e1-22245d16af36.png)

I think internet_nl_mail_legacy_category is useless and E-mail sending domain should be fixed.

**Comment by stitch** [comment]
Cannot reproduce, probably fixed a while ago
