### ISSUE TITLE
API & Dashboard performance limits

### ISSUE THREAD

**Issue by dennisbaaten** [internetstandards/Internet.nl-dashboard#359]
See the issue under the Internet.nl repository: https://github.com/internetstandards/Internet.nl/issues/671

**Comment by stitch** [comment]
* 25k domains can be added on the dashboard, but too many workers cause some trouble with limited ram on accept, this will be parameterized
* The list of 25k domains loads, albeit slowly

**Comment by stitch** [comment]
The API has some bottlenecks (probably chained tasks amplification), so until that is finished we cannot really up the amount of domains supported here. Closing this for now and we can re-open this when the need arises for even higher limits.
