### ISSUE TITLE
Make the 'average' column in adoption bar charts optional

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#36]
The average percentage is a useful value, but I don't want it displayed every time, since some charts are already quite cluttered.

**Comment by robinbzk** [comment]
Het goede van de oplossing die gekozen is in het dashboard om gemiddelden te tonen, is dat het gemiddelde dynamisch berekent wordt afhankelijk van de geselecteerde standaarden.
Ik zou dít gemiddelde echter optioneel willen maken, want het kost ook weer screenspace. Dit zou je eventueel per categorie kunnen aangeven, of één keer bovenaan de instellingen als optie.

This is linked to https://github.com/internetstandards/Internet.nl-dashboard/issues/51

**Comment by stitch** [comment]
Averages are optional now, it's also possible to exclusively show the average.

![image](https://user-images.githubusercontent.com/333846/62130381-35192b00-b2d9-11e9-8976-3629d810e9fd.png)
