### ISSUE TITLE
Round off percentages in charts

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#37]
To increase readability visible percentages in the charts should be rounded off (no decimals).
If a user wants to know the percentage with decimals, the user can hover the mouse over the respective column.

**Comment by stitch** [comment]
Change to 1 digit behind the comma.

**Comment by stitch** [comment]
Labels are rounded, while the rest of the data (hover, tables) are in two decimals.

![image](https://user-images.githubusercontent.com/333846/68476750-e2ca9d00-022b-11ea-9ceb-ee28e25cea98.png)

![image](https://user-images.githubusercontent.com/333846/68476788-fb3ab780-022b-11ea-88d9-a5cd0444255e.png)

This rounding function has been used.
