### ISSUE TITLE
Clarify on report that only results of first selected report are shown

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#38]
Would be good to clarify that when you select multiple reports, only the detailed results of the first selected report are shown and can be exported.
![afbeelding](https://user-images.githubusercontent.com/28256969/60653331-23637580-9e4a-11e9-9a85-f72c93b99bdb.png)
![afbeelding](https://user-images.githubusercontent.com/28256969/60653366-30806480-9e4a-11e9-99fa-f6b43ff3289e.png)

**Comment by stitch** [comment]
Het belangrijkste even toegevoegd, maar is wel wat summier. De vertaling is aan te passen.

![image](https://user-images.githubusercontent.com/333846/62131134-db196500-b2da-11e9-952d-10844a2a387f.png)

![image](https://user-images.githubusercontent.com/333846/62131143-dfde1900-b2da-11e9-9823-cb434a8e1bf1.png)
