### ISSUE TITLE
Sort order of comparative bar charts based on order of report selection

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#39]
Would be better to sort the bar comparative bar charts based on the order in which you select reports you want to compare.

![afbeelding](https://user-images.githubusercontent.com/28256969/60653712-de8c0e80-9e4a-11e9-95a0-3cd3e3f5a0ff.png)

![afbeelding](https://user-images.githubusercontent.com/28256969/60653696-d59b3d00-9e4a-11e9-9ab9-e2f0af1d77f0.png)

**Comment by stitch** [comment]
Due to async loading, the order of the reports in "compare_charts" was not correct. This has been solved by using a fixed index for each report and using a different way to set specific indexes in Vue.
