### ISSUE TITLE
Add unique labels per test type for repeated tests (DNSSEC/RPKI)

### ISSUE THREAD

**Issue by WKobes** [internetstandards/Internet.nl-dashboard#397]
There is currently an incorrect label for RPKI here:

https://github.com/internetstandards/Internet.nl-dashboard/blob/12efe7d0aa4bb3b29160d45ab32c39c2222a87aa/dashboard/internet_nl_dashboard/logic/internet_nl_translations.py#L348

valid should be exists.

However, there is an overarching problem with labels in the export. 

For IPv6, the label specifies which test it contains: "IPv6 addresses for name servers", "IPv6 reachability of name servers", "IPv6 addresses for mail server(s)"

For DNSSEC, this is not mentioned: "DNSSEC existence" "DNSSEC validity"

For RPKI, neither: "Route Origin Authorisation existence", "Route announcement validity"

We should alter this to include what is tested (webserver, mailserver, nameserver, nameserver of mailserver)

**Comment by stitch** [comment]
This seems to be partly solved via labels of their parent categories. But not for all cases. For example:

DNSSEC:
![image](https://user-images.githubusercontent.com/333846/206672633-72ef3357-5b58-48b7-8b0f-280705f0f5af.png)

RPKI:
![image](https://user-images.githubusercontent.com/333846/206672913-77cb6172-f5b4-4757-8e51-fee1b56eb2c7.png)

IPv6 (missing this info)
![image](https://user-images.githubusercontent.com/333846/206673079-910cf60c-5b4b-4f0e-889d-3fed8c5e92ba.png)

These labels are imported from internet.nl. If these are added/changed over there (and thus also in the internet.nl site) its easy to also use those same labels here.

Would that be the solution?

**Comment by stitch** [comment]
It's at least all the web_mail labels:

* detail_web_mail_ipv6_ns_reach_label
* detail_web_mail_ipv6_ns_aaaa_label
* detail_web_mail_rpki_ns_exists_label
* detail_web_mail_rpki_ns_valid_label

**Comment by WKobes** [comment]
Another wrong label here:

https://github.com/internetstandards/Internet.nl-dashboard/blob/12efe7d0aa4bb3b29160d45ab32c39c2222a87aa/dashboard/internet_nl_dashboard/logic/internet_nl_translations.py#L348

**Comment by stitch** [comment]
The labels mentioned above have been fixed for a while now. The remaining issue is that the parent category is not mentioned in the spreadsheet export. This makes it hard to understand what the result is about.

Here is the example about RPKI:
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/87fdd730-3e04-409a-ad4c-6b67123d4ec3)

Solution for now is to add parent categories as with the report in the web interface

**Comment by stitch** [comment]
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/07f9f177-3e6d-4e3c-ad07-825c223d64df)
