### ISSUE TITLE
Duplicate report generated from single scan

### ISSUE THREAD

**Issue by WKobes** [internetstandards/Internet.nl-dashboard#398]
Scan conducted on acceptation environment resulted in two identical reports. No clear reason why.

https://dev.batch.internet.nl/api/batch/v2/requests/166e56ea0d93464aaea9b17696d2ccd9/results

The list was scanned for both mail and web. This only happened for the web scan (scan no 5190)

Scan steps:

![image](https://user-images.githubusercontent.com/9413731/205939479-5de7deba-4703-4eb9-a93a-b7a63c5a668a.png)

**Comment by stitch** [comment]
I've probably set that to 'imported scan results' by hand while debugging, causing the next steps to be performed again.
