### ISSUE TITLE
Add 'legend of used icons' to detail report

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#41]
Similar to how there is a legend of used icons on the Domains page, it would be good to add a legend of used icons on the report.

![afbeelding](https://user-images.githubusercontent.com/28256969/60653985-6540eb80-9e4b-11e9-9938-c083b5d01234.png)

**Comment by stitch** [comment]
Done

![image](https://user-images.githubusercontent.com/333846/62065044-74d70880-b22e-11e9-8d4b-d8076a88a37a.png)
