### ISSUE TITLE
Dashboard does not reject invalid domain names

### ISSUE THREAD

**Issue by WKobes** [internetstandards/Internet.nl-dashboard#410]
We found a case where a domain name was added with invisible shy hyphens:

`pro­lan­der.nl` 

This domain contains invisible hypens (pro-lan-der.nl) which are invalid characters in domain names.

The dashboard lists simply store the invalid domain names, making it very hard to identify why testing the domain fails. It would be best if the domain name would be rejected, since it contains invalid characters.

**Comment by stitch** [comment]
Unicode control characters are now filtered out, meaning prolander.nl will be used.

Rejecting these types of accident can be annoying, especially when copying from 'contaminated' sources. The unstructured input should be accepting as many domains as possible. Showing a rejection for a domain where no visible issue seems present is just frustrating.

https://stackoverflow.com/questions/4324790/removing-control-characters-from-a-string-in-python
