### ISSUE TITLE
Resolving CNAME's / pre-check issue

### ISSUE THREAD

**Issue by bwbroersma** [internetstandards/Internet.nl-dashboard#412]
When adding `www.nic.cy` I got the error:
> Domain did not match scanning criteria at the time the scan was initiated. The scanning criteria are an SOA DNS record (not NXERROR) for mail and an A or AAAA DNS record for web. This domain is ignored in all statistics.

Is there a reason to not do CNAME resolving, or is there something else failing?

**Comment by stitch** [comment]
Seems fine on acc.

Web:
![image](https://user-images.githubusercontent.com/333846/233067103-322a9f60-b768-49f4-8312-47d16749d1e6.png)



Mail:
![image](https://user-images.githubusercontent.com/333846/233066980-ab45d088-ab48-44d3-a344-bbb2aaf374f1.png)

**Comment by bwbroersma** [comment]
Is it fixed accidentally with something else, or a known configuration difference?
BTW what about the pre-check that is done during the adding of the domain? On production I still get a 🚫:
![image](https://user-images.githubusercontent.com/4252918/233485561-b5d428be-e609-4184-bd6d-eae1d2fb5c6a.png)
