### ISSUE TITLE
Add 'base-uri' and 'form-action' directive to CSP header of Internet.nl dashboard domains itself

### ISSUE THREAD

**Issue by baknu** [internetstandards/Internet.nl-dashboard#413]
Check: https://github.com/internetstandards/Internet.nl/issues/900

**Comment by baknu** [comment]
Also for ipv6kaart.internet.nl

**Comment by aequitas** [comment]
The ipv6kaart CSP entries are added as well. I could not yet set a proper secure value for `script-src` as it breaks functionality. W'll have to look into that at a later point.
