### ISSUE TITLE
Add signup for for use of dashboard / api

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#419]

**Comment by stitch** [comment]
First version implemented, waiting for feedback by @dennisbaaten 

<img width="672" alt="image" src="https://user-images.githubusercontent.com/333846/233062801-6c3b2d0c-5be6-4f92-ad05-8f77be8fb8f3.png">

**Comment by stitch** [comment]
Waiting for feedback

**Comment by stitch** [comment]
feedback processed

**Comment by dennisbaaten** [comment]
Working on this again. I just tried the form again. Keeps "loading" without progress. We've had this before.
