### ISSUE TITLE
Speed up dashboard interface

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#425]
For 10.000 domains should load in a few seconds

**Comment by stitch** [comment]
inspiration: https://github.com/sveltejs/svelte-virtual-list

**Comment by bwbroersma** [comment]
The Vue version: https://github.com/tangbc/vue-virtual-scroll-list

**Comment by stitch** [comment]
Opties om te onderzoeken: tree shaking, lazy loading routes

**Comment by bwbroersma** [comment]
I notices in Edge on my managed Windows work system, displaying [the public report with 1775 domains](https://dashboard.internet.nl/#/shared/report/websiteregister_rijksoverheid_web_jan_23) and then clicking on 'details' below HTTPS, it will fire 3 'wait / exit' popups and eventually finishes, but it takes 2GB of extra memory (gone when closing the tab).

On my own Linux desktop system with :fox_face: Firefox Nightly I get a similar message when pressing on HTTPS details:
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/4252918/958a54ef-db22-4379-8e53-ffce3bbbb80d)
It shows 2.46 GB for this one tab in `about:performance`:
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/4252918/6ea91e1a-44af-4da9-bd14-07861de1beb7)

@stitch could you add the public websiteregister rijksoverheid report with 1775 domains to acc?
