### ISSUE TITLE
Password change functionality

### ISSUE THREAD

**Issue by WKobes** [internetstandards/Internet.nl-dashboard#427]
Allow users to change their own dashboard account password, preferably in the regular front-end

**Comment by stitch** [comment]
This has been solved with the allauth library, which also supports a ton of other authentication platforms including saml. It also has second factor support. We might move to this library for all authentication, but that requires 36 accounts with second factor to change as well.

The library also supports other flows such as password resets. So i think it is worth while to move to this platform and even check if we can just transfer the OTP devices.

**Comment by stitch** [comment]
Created a new ticket for further discussion.
