### ISSUE TITLE
add version number behind login

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#428]

**Comment by bwbroersma** [comment]
The version number is not shown in ACC nor production, where should it be?

**Comment by stitch** [comment]
Still a mystery to me. The build seems to create the version file properly. See:
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/188ce9d4-113b-4dcb-bddd-e3a8b465feb2)

The dashboard seems to read it properly, see:
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/5e81df25-6eb4-4fb8-91a5-bd2c730af6f7)

So let's see if this still occurs on the next 4.3 rollout. If so then continue debugging. Moved to 4.3 for administrative purposes.

**Comment by stitch** [comment]
Add several tricks to the build, still no result. Handing this over.

**Comment by stitch** [comment]
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/97c3d775-0381-4fc1-befd-db6a96e88df7)
