### ISSUE TITLE
Extend the keywords and descriptions

### ISSUE THREAD

**Issue by mdavids** [internetstandards/Internet.nl-dashboard#431]
For example:

https://github.com/internetstandards/Internet.nl-dashboard-frontend/blob/271f4cbe4b7d91337eea4b7e2a881e3a42e54283/src/components/SiteMenu.vue#L325

We could add stuff there. `RPKI` comes to mind for example. Perhaps also `RFC9116`.

**Comment by stitch** [comment]
Keywords and description added in the index.html, the sitedescription was changed according to the internet.nl site.

See https://github.com/internetstandards/Internet.nl-dashboard-frontend/pull/62
