### ISSUE TITLE
Feedback which domains were invalid when adding domains

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#44]
When I'm adding a set of domains through the user interface (for example 563 domains), I get feedback how many valid domains were added (for example 561 domains), but I would also want feedback on the domain names which were invalid/not added (for example the 2 invalid domains www.example.xyz and www.example.abc).

**Comment by stitch** [comment]
This is an example of the check already in place:

Suppose we add this:
![image](https://user-images.githubusercontent.com/333846/62043763-763e0c00-b201-11e9-8599-5a6c73548308.png)

We'll get feedback that one domain is invalid. Note that .xyz is a valid top level domain with >2M registrations. Also .abc is a valid top level domain: see nic.abc :) .abc has about 19 domain registrations.

![image](https://user-images.githubusercontent.com/333846/62043823-a9809b00-b201-11e9-8eeb-deacb64ffeed.png)

**Comment by stitch** [comment]
Retrying this will also show some domains are already in the list.

![image](https://user-images.githubusercontent.com/333846/62044064-4fcca080-b202-11e9-8b3d-6bf0726dd4b0.png)
