### ISSUE TITLE
Add results link and internet.nl score to downloadable reports (xlsx, csv, ods)

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#45]
The results link is needed for easy access to the individual results of that measurement.

The Internet.nl score is for useful for sorting and highlighting the results.

**Comment by stitch** [comment]
![image](https://user-images.githubusercontent.com/333846/62041264-83f09300-b1fb-11e9-91ae-2e3402a9ffda.png)
