### ISSUE TITLE
Add not_applicable and not_testable as possible values to downloadable reports (xlsx, csv, ods)

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#46]
In the downloadable reports (xlsx, csv, ods) the results that were not_applicable and not_testable are now marked as 0 (fail). There should be a different marking for the not_applicable and not_testable results to prevent confusion.

This is part of the reporting format for government measurements: see for example page 36 of https://www.forumstandaardisatie.nl/sites/bfs/files/proceedings/FS-190424.5A_Meting_informatieveiligheidstandaarden_begin_2019.pdf

**Comment by stitch** [comment]
![image](https://user-images.githubusercontent.com/333846/62041264-83f09300-b1fb-11e9-91ae-2e3402a9ffda.png)
