### ISSUE TITLE
Missing X-Frame-Options should not cause a regression when CSP frame-ancestors is used

### ISSUE THREAD

**Issue by i81b4u** [internetstandards/Internet.nl-dashboard#464]
When removing X-Frame-Options and using CSP frame-ancestors only, the dashboard classifies this as a regression. When looking at what web browsers support CSP frame-ancestors it's hard to argue that X-Frame-Options could be useful when using older web browsers. Even more so when restricting TLS protocols and ciphers not supported by those older web browsers anyway.

Please consider changing the current behaviour.

**Comment by baknu** [comment]
Relates to https://github.com/internetstandards/Internet.nl/issues/1157

**Comment by stitch** [comment]
The dashboard relies on the policies that are set in internet.nl. This issue has been moved to the internet.nl repository.
