### ISSUE TITLE
Add link to original report in excel spreadsheet

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#47]
"Is het mogelijk om uit een rapport over bv 200 sites de (perma-)links naar de detailrapporten in bijvoorbeeld de excel-export mee te krijgen of op een andere manier die links op een rijtje te krijgen, zodat ze makkelijker met lokale beheerders te (ver)delen zijn?"

**Comment by robinbzk** [comment]
See https://github.com/internetstandards/Internet.nl-dashboard/issues/45

**Comment by stitch** [comment]
![image](https://user-images.githubusercontent.com/333846/62041264-83f09300-b1fb-11e9-91ae-2e3402a9ffda.png)
