### ISSUE TITLE
A11Y: [object Object] text in visuallyhidden

### ISSUE THREAD

**Issue by bwbroersma** [internetstandards/Internet.nl-dashboard#479]
On any report page, e.g. the sample https://dashboard.internet.nl/#/shared/report/393709ec-b451-4ce9-8e7b-8595db3ac8ad
There is this generated part per hostname, probably done in JS:
```html
<span data-v-XXXXXXXX="" class="visuallyhidden"> View score and report from [object Object] on internet.nl.</span>
```
I think it should list the hostname instead.

**Comment by stitch** [comment]
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/952fafd7-21a2-48fe-9c0a-3d1b66a12599)
