### ISSUE TITLE
Unnecessary scroll in report table

### ISSUE THREAD

**Issue by hhoek** [internetstandards/Internet.nl-dashboard#480]
Unnecessary scroll in report table (Edge browser): 
![Webopname_16-10-2023_16422_dashboard internet nl](https://github.com/internetstandards/Internet.nl-dashboard/assets/144927270/9e896899-d6dc-4031-9dc8-26dcd32a65b1)

**Comment by stitch** [comment]
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/43ef8fb0-109b-4c60-8086-8a0bdef28c1f)
