### ISSUE TITLE
Finding (www.) subdomains never seem to finish

### ISSUE THREAD

**Issue by bwbroersma** [internetstandards/Internet.nl-dashboard#482]
"Add www\. subsubdomains" takes forever, stuck in "Finding subdomains".
1) The button should be renamed from "Add www\. subsubdomains" to "Add www\. subdomains"
2) See here a list of 259 domains:
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/4252918/c82ece36-0031-4d74-aea5-83297ece05d6)
3) The www\. are never shown/added to the list.

BTW the same problem occurs for small lists, e.g. with 2 apex domain names.

**Comment by stitch** [comment]
Solved. Task was not explicitly set to the storage queue and therefore not picked up.
