### ISSUE TITLE
Fix not_applicable and not_testable for DANE in forum standaardisatie view

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#50]
Adoptie DANE is gedaald. Volgens mij komt dat omdat de DANE resultaten in gevallen NIET_TESTBAAR en NOT_APPLICABLE niet als zodanig wordt aangemerkt in de Forum Standaardisatie view (wel in de STARTTLS en DANE view).

![afbeelding](https://user-images.githubusercontent.com/28256969/61009740-04963f00-a374-11e9-830d-bbc92c4a3780.png)

**Comment by robinbzk** [comment]
See #34

**Comment by stitch** [comment]
Fix in progress:
https://gitlab.com/internet-cleanup-foundation/web-security-map/merge_requests/351
