### ISSUE TITLE
Online application form

### ISSUE THREAD

**Issue by dennisbaaten** [internetstandards/Internet.nl-dashboard#501]
Some feedback regarding the current online application form (4.3):

- https;//dashboard.internet.nl states "Request access by sending an e-mail to..." --> if the form is finished we can remove this line.
- The captcha is always "42". Maybe we can use something like: https://mcaptcha.org/.
  - Remove the captcha from the signup details send by mail. I don't know if this is a lot of work, but I don't the field.
- Nature of organization
  - add short description "The API and Dashboard are only available for organizations that meet [specific requirements](https://github.com/internetstandards/Internet.nl-API-docs/blob/main/application_form/README.md). Please select the option that applies to you."
  - introduce new option "Hoster in the Hall of Fame for Hosters"
  - remove "other"
  - rename "Vital infrastructure" to "Category A vital infrastructure (NIS2)"
- Does the applicant also receive a CC of the email send to vraag@internet.nl?

**Comment by bwbroersma** [comment]
Because of spam it's probably not ideal to CC mail with user inputs to a mail address that is also an input. An option would be to send a boilerplate mail without user input to the mail address that is chosen, is that an option?

**Comment by stitch** [comment]
Added the label changes for nature of organization.

Before solving something that should be solved on our end: The form is very clear a submission has been made. After how many days the inquiry is made? And would they send this mail anyway after that amount of day regardless of a mail?

A captcha should only be improved when receiving some form of spam. As far as i can see this never happened, so that would solve no issue as all spam has been prevented.

**Comment by stitch** [comment]
https://acc.dashboard.internet.nl/#/signup

**Comment by dennisbaaten** [comment]
Nice! In the last line: "i agree to the terms"; can you add a link to the terms? (https://github.com/internetstandards/Internet.nl-API-docs/blob/main/terms-of-use.md)

**Comment by stitch** [comment]
> Nice! In the last line: "i agree to the terms"; can you add a link to the terms? (https://github.com/internetstandards/Internet.nl-API-docs/blob/main/terms-of-use.md)

To
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/20db2ebd-c05f-42e5-a308-4161a6014938)


From
![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/6e4bfb2c-f345-46f2-a94c-3833f29bcbd2)

**Comment by stitch** [comment]
Plain text mail toevoegen

**Comment by stitch** [comment]
* Not going to remove the 42
* Sending a templated message to the recipient, this is configurable in the admin panel
* Changed the signup text on the frontpage
* All other text changes have been processed
