### ISSUE TITLE
Add 'Gemiddelde webstandaarden' and 'Gemiddelde e-mailstandaarden' to forum standaardisatie view

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#51]
![afbeelding](https://user-images.githubusercontent.com/28256969/61010286-f34e3200-a375-11e9-83da-8bd7cbea246b.png)
Om bovenstaand diagram te kunnen maken, is een oplossing om bij de Forum Standaardisatie instellingen nog 2 selecties toe te voegen: Gemiddelde webstandaarden en Gemiddelde e-mailstandaarden. Dit zou dan een niet-dynamisch gemiddelde van alle betreffende Forum Standaardisatie standaarden zijn.

This is linked to https://github.com/internetstandards/Internet.nl-dashboard/issues/36

**Comment by stitch** [comment]
Example for web:

![image](https://user-images.githubusercontent.com/333846/62130818-1b2c1800-b2da-11e9-9da3-19c95fa9bee4.png)

**Comment by robinbzk** [comment]
Door de volgende opties aan te vinken...
- Bereken dynamisch het gemiddelde van alle zichtbare velden
- Toon alleen het dynamisch berekende gemiddelde 

...bereik je volgens mij hetzelfde effect als wat hier geïmplementeerd is, waardoor deze feature eigenlijk overbodig is geworden. Wat denk jij Elger?
