### ISSUE TITLE
Large domain lists: limit the number of domains via GUI upload and mention spreadsheet upload

### ISSUE THREAD

**Issue by baknu** [internetstandards/Internet.nl-dashboard#515]
As metioned in the release notes, dashboard [v4.3.0](https://github.com/internetstandards/Internet.nl-dashboard/releases/tag/v4.3) "targets to support creating lists and viewing reports up to 10.000 domains". However, when adding large sets of domains via the GUI this is slow without giving feedback to the user.  The spreadsheet upload functionality is therfore the preferred way for adding large sets of domains. This should be made clear in the GUI. 

Suggested solution: We could (1) limit the number of domains that can be uploaded via the GUI to 150 and (2) mention explicitly that uploading via a spreadsheet is the preferred way for large domain lists.

**Comment by stitch** [comment]
Try if a transaction speeds this up and add some measurements / benchmarks.

**Comment by stitch** [comment]
Added a GUI-only check for larger amounts of domains, which will guide (and force) the user to use the spreadsheet upload procedure when a larger amount of domains is detected. Too-large lists are ofc still checked server-side.

![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/549bea27-d5e2-49db-b497-fd9369f791ad)

**Comment by stitch** [comment]
Added progress bars to the upload. They are not perfect but help give an idea of what the status of the upload is.

![image](https://github.com/internetstandards/Internet.nl-dashboard/assets/333846/2a0988d4-a2ee-4b87-b5a4-f41066b4bb56)
