### ISSUE TITLE
Add a Content-Security-Policy header perhaps?

### ISSUE THREAD

**Issue by mdavids** [internetstandards/Internet.nl-dashboard#53]
See subject.

**Comment by stitch** [comment]
OK

**Comment by stitch** [comment]
Based on laboratory: https://addons.mozilla.org/en-US/firefox/addon/laboratory-by-mozilla/

The CSP should be, (and shows some issues with the site): 

`default-src 'none'; connect-src 'self'; font-src 'self'; form-action 'self'; img-src 'self' data: https://www.internet.nl; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://matomo.internet.nl/piwik.js; style-src 'self' 'unsafe-inline'`

**Comment by stitch** [comment]
CSP added in server config. Will be used on deploy.

**Comment by aequitas** [comment]
CSP config in https://github.com/internetstandards/Internet.nl-dashboard-server/pull/1/files still needs some tweaking

**Comment by aequitas** [comment]
PEBKAC, adblocker was turned on and gave false positives :)
