### ISSUE TITLE
Mail alerts on finished scheduled batch scan?

### ISSUE THREAD

**Issue by mdavids** [internetstandards/Internet.nl-dashboard#54]
I would appreciate an e-mail ping when my schedule batch scan is finished.

Maybe even including a nicely formatted overview of the results.

**Comment by stitch** [comment]
We're looking for a suitable SMTP host that we can use.

Todo: add settings for SMTP server. Add a mail.

**Comment by stitch** [comment]
Has been implemented, yet no SMTP server is configured yet.

**Comment by stitch** [comment]
Mails will be sent from: noreply@dashboard.internet.nl

Properties needed to set up sending mail:
EMAIL_HOST = ''
EMAIL_PORT = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False/True
EMAIL_USE_SSL = False/True

**Comment by stitch** [comment]
Step 1:

- [ ] E-Mails kunnen worden opgesteld en verstuurd in meerdere talen.
- [ ] E-Mails worden verstuurd vanaf een herkenbaar adres: dashboard@internet.nl
- [ ] Vanaf de acceptatie omgeving worden mails gestuurd vanaf dashboard-acc@internet.nl
- [ ] E-Mails worden verstuurd in HTML, om opmaak mogelijk te maken.
- [ ] E-Mails worden 'getemplate' opgesteld zodat ze makkelijk zijn bij te werken. Bijvoorbeeld: "Hi {receipient}. Your scan on {list_name} has finished. View the report at this link: {report_link}. Regards, internet.nl. {unsubscribe} {settings}".
- [ ] E-Mails bevatten een directe unsubscribe link voor dit type mail: een gebruiker hoeft niet ingelogd te zijn om zich uit te schrijven. (anti spam wetgeving)
- [ ] E-Mails bevatten een directe link naar de instellingen voor het versturen van mail.
- [ ] E-Mails bevatten links om direct naar het rapport te gaan.
- [ ] E-Mails worden (gender)neutraal opgesteld: geen specifieke aanhef (en dus persoonsgegevens) zijn nodig.
Mail moet zo worden opgesteld dat deze niet automatisch in de spam terecht komen. 100% score op de afzender spreekt voor zich, maar ook de indeling/details van de mail heeft hier invloed op. Dit betreft finetuning.



Stap 2:
- [ ] Gebruiker kan zelf een e-mail adres instellen waarop mails worden gestuurd. 
- [ ] Gebruiker kan zelf aangeven of deze mail wil ontvangen na het afronden van een scan.
- [ ] Gebruiker kan uit de ondersteunde talen aangeven waarin de mail wordt gestuurd.
- [ ] Gebruiker wordt in de interface op de hoogte gesteld dat het sturen van mails kan.
- [ ] Het ontvangen van e-mail is opt-in.

- [ ] Bij een verwerkingsovereenkomst: Tonen van en het wijzen naar hoe data wordt verwerkt, dit kan een linkje zijn, maar er kan ook een vraag worden gesteld. De tekst voor deze overeenkomst is in te stellen in de beheerspagina's. (NB: een korte heldere tekst is het beste)

**Comment by stitch** [comment]
Some progress:

Settings:
![image](https://user-images.githubusercontent.com/333846/95223016-66548b80-07f9-11eb-8c1a-eb1ab686e2d5.png)


Email in menu:
![image](https://user-images.githubusercontent.com/333846/95223091-7a988880-07f9-11eb-8c57-8e3e4ab6d682.png)


Template editing:
![image](https://user-images.githubusercontent.com/333846/95223155-8b48fe80-07f9-11eb-9e2c-b6403d4548ba.png)

Mail sending configuration:
![image](https://user-images.githubusercontent.com/333846/95223199-9a2fb100-07f9-11eb-8c86-ec2c8151d9c4.png)
