### ISSUE TITLE
Comparison diagram: not all percentages are shown

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#64]
![afbeelding](https://user-images.githubusercontent.com/28256969/62240546-814a9500-b3d7-11e9-8bd2-5c9fd66f0377.png)
maybe https://github.com/internetstandards/Internet.nl-dashboard/issues/37 helps
Not a big issue by the way, since we have never put this exact diagram in a report.

**Comment by stitch** [comment]
All are shown and can overlap
