### ISSUE TITLE
Comparison diagram enhancements

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#65]
![afbeelding](https://user-images.githubusercontent.com/28256969/62241273-2154ee00-b3d9-11e9-9a5b-6d07561d3834.png)

Something that should probably be changed is the diagram title of comparison diagrams. Currently it references the first selected report, in this case "mail_rijk, 60 domeinen", perhaps when its a comparison diagram the title should be changed to something more accurate like _Vergelijking adoptie van standaarden van 5 rapporten_.

A nice enhancement would be to add the number of domains (per report) in the legend.

**Comment by stitch** [comment]
![image](https://user-images.githubusercontent.com/333846/63212604-62ead600-c107-11e9-80c9-7dc055ab4e15.png)
