### ISSUE TITLE
Separate individual report feature and report comparison feature

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#67]
Perhaps in a next version we should separate the individual report feature and report comparison feature to different menu items in order to reduce complexity.

Sometimes things get weird when you first select a report and then compare that report to another report, and then reduce the amount of report to 1 report again. In some occassions (not always reproduceable the " Average adoption of standards over multiple reports " section is still shown (but empty) ) Might be a connection issue.

By separating the two features, we could also remove the "Dit overzicht laat alleen de resultaten van het het eerst geselecteerde rapport zien." line.

Another argument for separating these views is that the the _Adoptie van standaarden over tijd_ section is not always a 'relevant section' in the UI when comparing reports, because you could be comparing reports from different domain groups.

**Comment by stitch** [comment]
When comparing, everything on the page should understand comparison, including the "vulnerabilities over time" and the reported issues themselves (#74).

Or nothing should change and comparison should be an extra page with those functionalities (under the hood they will probably use the same code).

For further development see #74.
