### ISSUE TITLE
Wrong calculations for averages when not_applicable or not_testable

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#68]
For example take report 41 gemeenten_mail_nieuw of august 1.
It has a total of 365 domains.
If you look at DANE, there are in total 14 results not_applicable or not_testable.

This would mean that to calculate the average, the following calculation is made:
157/(365-14)*100%=44,73%

However in the report the % for DANE is different:
![afbeelding](https://user-images.githubusercontent.com/28256969/62245152-3f265100-b3e1-11e9-99a0-4272b8990248.png)

The same problem happens with STARTTLS_NCSC (should be 72,93% instead of  73.24%)
The same problem happens with DKIM (should be 93,13% instead of  93.15%)
Probably the same also happens with STARTTTLS and DNSSEC_MX (and underlying tests).

In general, the solution is that when there is a result that can't be attributed clearly to "true" or "false", we withhold these (not_applicable, not_testable) results from the total when calculating the average.

**Comment by stitch** [comment]
Removed not_applicable and not_testable from total.

![image](https://user-images.githubusercontent.com/333846/63212655-2b305e00-c108-11e9-8f95-715fa7b1a1ee.png)
