### ISSUE TITLE
Excel output totals

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#69]
![afbeelding](https://user-images.githubusercontent.com/28256969/62245927-e8ba1200-b3e2-11e9-8143-6931303aa3b7.png)
Perhaps in a new version we can add 'Contains not_applicable' and 'Contains not_testable') to the totals table.
'Contains ?' doesn't seem to happen at all, so could probably be removed.

**Comment by stitch** [comment]
![image](https://user-images.githubusercontent.com/333846/63212646-15bb3400-c108-11e9-94ab-32ed21f4b5a4.png)
