### ISSUE TITLE
Change domain icon to 'scientific notation' n=355

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#71]
Instead of domain icon, which could be confusing, use the following notation:

Ex: `totaal_mail 20 augustus 2019, n=561
`
Follow up of https://github.com/internetstandards/Internet.nl-dashboard/issues/65

**Comment by stitch** [comment]
Easy.

**Comment by stitch** [comment]
![image](https://user-images.githubusercontent.com/333846/68380964-17b5f180-0151-11ea-9eec-b5d45bedfc54.png)

**Comment by stitch** [comment]
Done.
