### ISSUE TITLE
In Excel output, both mail and web, change legacy category name to nlgov_complyorexplain

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#72]
In Excel output, both mail and web test, change `legacy `category name to `nlgovernment_complyorexplain`

**Comment by stitch** [comment]
One label / translation change

![image](https://user-images.githubusercontent.com/333846/66568947-ca069300-eb6a-11e9-8445-c4bdd3e4e5ea.png)

**Comment by stitch** [comment]
Done
