### ISSUE TITLE
Automatically add known subdomains

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#73]
Would be good to add a feature in the future to automatically add all known subdomains of a domain

**Comment by robinbzk** [comment]
https://github.com/gnebbia/pdlist

**Comment by stitch** [comment]
How to deal with wildcard domains?

**Comment by stitch** [comment]
Questions that come to mind:

* Only on top level domain and find everything
* Limit on found subdomains?
* Is not guaranteed to be complete

**Comment by stitch** [comment]
Low prio, after www.

**Comment by stitch** [comment]
Will be difficult to add during a scan. Has a lot of drawbacks.
