### ISSUE TITLE
Multiple users for the same lists/reports

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#77]
Some organizations would like to have multiple users that have access to the same set of domains and resulting reports.

"En is het mogelijk meerdere gebruikers te definiëren en eventueel voor een gedeelte te autoriseren. Ik zou namelijk graag het invoeren van de domeinen willen delegeren aan de persoon die de domeinen en certificaten beheert en dan zelf de rapportage te beheren. ."

**Comment by stitch** [comment]
This is already implemented. It is possible to add multiple users to the same account.

To do this use the admin interface, and under a user, specify what account they are in:
![image](https://user-images.githubusercontent.com/333846/66572670-adba2480-eb71-11e9-840f-f48b726b84da.png)

This is also how the "change account" feature works for admins.
