### ISSUE TITLE
Show number of domains in a list in the Domeinen view under "Over deze lijst"

### ISSUE THREAD

**Issue by robinbzk** [internetstandards/Internet.nl-dashboard#85]

**Comment by stitch** [comment]
Add it here:

![image](https://user-images.githubusercontent.com/333846/66575517-536f9280-eb76-11e9-978d-ee05d52a277b.png)

**Comment by stitch** [comment]
![image](https://user-images.githubusercontent.com/333846/69152134-32d31a80-0adc-11ea-80e5-3fb45c419177.png)
