### ISSUE TITLE
Status IPv6 https not reachable

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#86]
Uptimerobot?

**Comment by aequitas** [comment]
Requirements:
- [ ] uptimerobot account
- [ ] uptimerobot terraform config
- [ ] AAAA only dns record `ipv6.dashboard.internet.nl
- [ ] CNAME `status.dashboard.internet.nl` -> `stats.uptimerobot.com`

**Comment by aequitas** [comment]
https://stats.uptimerobot.com/QNK68hkrKw

**Comment by stitch** [comment]
Subdomains will be requested once the header changes have been implemented at uptimerobot. This means that it also receives a 100% score on internet.nl tests.

**Comment by stitch** [comment]
AAAA records requested

**Comment by stitch** [comment]
@aequitas AAAA records have been created. The uptimerobot needs to be adjusted to match the ipv6 addresses: https://stats.uptimerobot.com/QNK68hkrKw

**Comment by stitch** [comment]
Fixed!
